package org.igooo.mongo.autogenerated

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class MongodbAutoGeneratedApplicationTests {

    @Test
    fun contextLoads() {
    }

}
