package org.igooo.mongo.autogenerated

import org.springframework.boot.ApplicationRunner
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.data.mongodb.core.MongoTemplate
import org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener
import org.springframework.data.mongodb.core.mapping.event.BeforeConvertEvent

@SpringBootApplication
class MongodbAutoGeneratedApplication {

    @Bean
    fun run(mongoTemplate: MongoTemplate): ApplicationRunner =
        ApplicationRunner { _ ->
            val product = Product("iPhone")
            mongoTemplate.save(product)
            println(product)
        }

    @Bean
    fun productMongoEventListener(sequenceGenerator: SequenceGenerator): AbstractMongoEventListener<Product> =
        object : AbstractMongoEventListener<Product>() {
            override fun onBeforeConvert(event: BeforeConvertEvent<Product>) {
                event.source.id = sequenceGenerator.getNextSequence("product")
            }
        }
}

fun main(args: Array<String>) {
    runApplication<MongodbAutoGeneratedApplication>(*args)
}
