package org.igooo.mongo.autogenerated

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

@Document("product")
data class Product(val name: String, @Id var id: Long? = null)