package org.igooo.mongo.autogenerated

import org.springframework.data.mongodb.core.FindAndModifyOptions.options
import org.springframework.data.mongodb.core.MongoTemplate
import org.springframework.data.mongodb.core.query.Query
import org.springframework.data.mongodb.core.query.Update
import org.springframework.data.mongodb.core.query.isEqualTo
import org.springframework.stereotype.Component

@Component
class SequenceGenerator(private val mongoTemplate: MongoTemplate) {

    fun getNextSequence(id: String): Long = mongoTemplate.findAndModify(
        Query(DatabaseSeq::id.isEqualTo(id)),
        Update().inc(DatabaseSeq::seq.name, 1L),
        options().returnNew(true).upsert(true),
        DatabaseSeq::class.java
    )?.seq ?: 1L

}